stages:
  - fetch_changes
  - build
  - test

fetch_changes:
  stage: fetch_changes
  script:
    - git remote add github https://github.com/RaiqaRasool/Technical-Documentation.git
    - git fetch github
    - git checkout main
    - git merge github/main
  only:
    - web

build:
  stage: build
  script: 
    - echo "Building Project"


test:
  stage: test
  script:
    - echo "Testing Project"